/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ScreenshotsRouteImport } from './routes/screenshots'
import { Route as HiddenChargesRouteImport } from './routes/hidden-charges'
import { Route as GstTaxRouteImport } from './routes/gst-tax'
import { Route as EmisRouteImport } from './routes/emis'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotsRoute = ScreenshotsRouteImport.update({
  id: '/screenshots',
  path: '/screenshots',
  getParentRoute: () => rootRouteImport,
} as any)
const HiddenChargesRoute = HiddenChargesRouteImport.update({
  id: '/hidden-charges',
  path: '/hidden-charges',
  getParentRoute: () => rootRouteImport,
} as any)
const GstTaxRoute = GstTaxRouteImport.update({
  id: '/gst-tax',
  path: '/gst-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const EmisRoute = EmisRouteImport.update({
  id: '/emis',
  path: '/emis',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/emis': typeof EmisRoute
  '/gst-tax': typeof GstTaxRoute
  '/hidden-charges': typeof HiddenChargesRoute
  '/screenshots': typeof ScreenshotsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/emis': typeof EmisRoute
  '/gst-tax': typeof GstTaxRoute
  '/hidden-charges': typeof HiddenChargesRoute
  '/screenshots': typeof ScreenshotsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/emis': typeof EmisRoute
  '/gst-tax': typeof GstTaxRoute
  '/hidden-charges': typeof HiddenChargesRoute
  '/screenshots': typeof ScreenshotsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/emis'
    | '/gst-tax'
    | '/hidden-charges'
    | '/screenshots'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards'
    | '/emis'
    | '/gst-tax'
    | '/hidden-charges'
    | '/screenshots'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/emis'
    | '/gst-tax'
    | '/hidden-charges'
    | '/screenshots'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  EmisRoute: typeof EmisRoute
  GstTaxRoute: typeof GstTaxRoute
  HiddenChargesRoute: typeof HiddenChargesRoute
  ScreenshotsRoute: typeof ScreenshotsRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshots': {
      id: '/screenshots'
      path: '/screenshots'
      fullPath: '/screenshots'
      preLoaderRoute: typeof ScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidden-charges': {
      id: '/hidden-charges'
      path: '/hidden-charges'
      fullPath: '/hidden-charges'
      preLoaderRoute: typeof HiddenChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst-tax': {
      id: '/gst-tax'
      path: '/gst-tax'
      fullPath: '/gst-tax'
      preLoaderRoute: typeof GstTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emis': {
      id: '/emis'
      path: '/emis'
      fullPath: '/emis'
      preLoaderRoute: typeof EmisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  EmisRoute: EmisRoute,
  GstTaxRoute: GstTaxRoute,
  HiddenChargesRoute: HiddenChargesRoute,
  ScreenshotsRoute: ScreenshotsRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
